### PR TITLE
Add failing test

### PR DESCRIPTION
**Pull request by mernst**
Here is another problem with `@EnsuresCalledMethods`.

### CODE REVIEW

**Comment by kelloggm** [comment]
This is a Checker Framework bug, not an OCC bug - there's nothing here that has anything to do with MustCall or the Resource Leak Checker. We should open an issue for this in the CF and then reference it in the SW justification.

**Comment by msridhar** [comment]
I am surprised we don't have tests for this already.  I think this could be causing some false positives in our other case studies as well /cc @Nargeshdb

**Comment by mernst** [comment]
When I remove the `@Owning` annotation and run on typetools (that is, Checker Framework master), the test passes.

**Comment by kelloggm** [comment]
I suspect that the problem is that https://github.com/typetools/checker-framework/pull/4683 is not in the version of the CF that we're using (we're using 3.12.0, but that PR wasn't in a release until 3.14.0).

**Comment by msridhar** [comment]
> I suspect that the problem is that [typetools/checker-framework#4683](https://github.com/typetools/checker-framework/pull/4683) is not in the version of the CF that we're using (we're using 3.12.0, but that PR wasn't in a release until 3.14.0).

Not sure this is the issue, as the logic in https://github.com/typetools/checker-framework/pull/4683 is already included in this checker, which subclasses the Called Methods Checker, see here:

https://github.com/kelloggm/object-construction-checker/blob/3c51a52ceba34ee7710cd74d181d2a5ec5ba9ca6/object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionTransfer.java#L84

**Comment by kelloggm** [comment]
@msridhar you're right, I'd forgotten. There must be some other difference between how this is handled here and how it's handled in the CF.

@mernst given our limited time budget, I think we should just live with these false positives for now. We can justify them with a link to this issue.

**Comment by mernst** [comment]
We already have an appropriate false positive warning suppression for the relevant method in Zookeeper's `ObserverMaster.java`.

**Pull request closed without merging**
