### PR TITLE
Documentation on Lombok/AutoValue defaulting

### PR DESCRIPTION
**Pull request by kelloggm**
Mike pointed out that we didn't have good docs for the Lombok/AutoValue defaulting rules.

Mike, are these docs sufficient to help you understand what is going on? If not, what other information do you need?

Manu, have I gotten the AutoValue rules correct? Are there any caveats like those I added for Lombok at the end that I don't know about?

### CODE REVIEW

**Comment by msridhar** [comment]
I am not sure it is super beneficial to document all the special cases we have handled for Lombok and AutoValue.  As an alternative, we could say that for the `build()` method, we add `@CalledMethods` for all the required setter calls, handling various special cases.  Isn't that basically the only thing that is "visible" to a user of the tool?  If we're writing documentation for developers building on the tool that is different.

We could also say that we may have missed some special cases and marked some `Builder` setters as required when in fact they are not, and that users should file an issue if they find such a case.

**Comment by mernst** [comment]
I agree that brevity, and focus on what users care about, will lead to the most helpful documentation.

**Comment by kelloggm** [comment]
I think it is important to have complete documentation of exactly what annotations we are placing in users' code automatically. This is especially important for Lombok, because experienced users often partially overwrite Lombok's generated code and insert their own versions. In order for such users to figure out how our tool will interact with their customizations, they'll need access to this information.

This text appears at the end of the README, and is linked earlier on for curious readers. It is otherwise there only for experienced users. Since our README is somewhat disorganized, that's only signaled by its placement at the end.

I am strongly of the opinion that this text needs to appear somewhere. I'm open to putting it into a "for advanced users" section or document, but none exists. Would that be preferable?

**Comment by msridhar** [comment]
Sounds good @kelloggm. I don’t think devs do any hacking of AutoValue-generated code so the details are less important there. I’m fine with landing this, or I can make a pass on it later / tomorrow morning.

**Comment by kelloggm** [comment]
This is just documentation, so it can wait for you to do a pass - there's no hurry.

Hacking on what Lombok generates is fairly common.

**Pull request merged**
