### PR TITLE
Instructions for using the checker from Maven Central

### PR DESCRIPTION
**Pull request by mernst**
These instructions are my best guess, but they don't seem to work.

For example, try this:

mernst

```
git clone https://github.com/mernst/java-webauthn-server.git --branch object-construction-checker
cd java-webauthn-server
./gradlew build
```

The end of the output is:

```
...
> Task :buildSrc:build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mernst/tmp/java-webauthn-server/build.gradle' line: 190

* What went wrong:
A problem occurred evaluating root project 'webauthn-server-parent'.
> Could not find method checkerFramework() for arguments [net.sridharan.objectconstruction:object-construction-checker:0.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

### CODE REVIEW

**Comment by kelloggm** [comment]
I believe that there are two unrelated problems here:
* the Gradle plugin doesn't seem to handle subprojects gracefully. I will look into why this is happening. For now, I've committed a "fix" in the `build.gradle` file of `java-webauth-server` to https://github.com/kelloggm/java-webauthn-server/tree/object-construction-checker (see d29637ddcae0c0b992d5090ce8a3a2beccba12d5).
* The version of the object construction checker on Maven doesn't resolve its dependencies correctly. Running `./gradlew build` using the modified `build.gradle` file that handles subprojects results in this output:
```bash
!object-construction-checker ~/Research/tmp/java-webauthn-server> ./gradlew clean build

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> Could not resolve all files for configuration ':webauthn-server-attestation:checkerFramework'.
   > Could not find net.sridharan.objectconstruction:returnsrcvr-checker:0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/kelloggm/.m2/repository/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/maven-metadata.xml
       - file:/Users/kelloggm/.m2/repository/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/returnsrcvr-checker-0.1-SNAPSHOT.pom
       - file:/Users/kelloggm/.m2/repository/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/returnsrcvr-checker-0.1-SNAPSHOT.jar
       - http://repo.maven.apache.org/maven2/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/maven-metadata.xml
       - http://repo.maven.apache.org/maven2/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/returnsrcvr-checker-0.1-SNAPSHOT.pom
       - http://repo.maven.apache.org/maven2/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/returnsrcvr-checker-0.1-SNAPSHOT.jar
     Required by:
         project :webauthn-server-attestation > net.sridharan.objectconstruction:object-construction-checker:0.1
   > Could not find net.sridharan.objectconstruction:returnsrcvr-qual:0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/kelloggm/.m2/repository/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/maven-metadata.xml
       - file:/Users/kelloggm/.m2/repository/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/returnsrcvr-qual-0.1-SNAPSHOT.pom
       - file:/Users/kelloggm/.m2/repository/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/returnsrcvr-qual-0.1-SNAPSHOT.jar
       - http://repo.maven.apache.org/maven2/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/maven-metadata.xml
       - http://repo.maven.apache.org/maven2/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/returnsrcvr-qual-0.1-SNAPSHOT.pom
       - http://repo.maven.apache.org/maven2/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/returnsrcvr-qual-0.1-SNAPSHOT.jar
     Required by:
         project :webauthn-server-attestation > net.sridharan.objectconstruction:object-construction-checker:0.1 > net.sridharan.objectconstruction:object-construction-qual:0.1
> Could not resolve all files for configuration ':webauthn-server-core:checkerFramework'.
   > Could not find net.sridharan.objectconstruction:returnsrcvr-checker:0.1-SNAPSHOT.
     Required by:
         project :webauthn-server-core > net.sridharan.objectconstruction:object-construction-checker:0.1
   > Could not find net.sridharan.objectconstruction:returnsrcvr-qual:0.1-SNAPSHOT.
     Required by:
         project :webauthn-server-core > net.sridharan.objectconstruction:object-construction-checker:0.1 > net.sridharan.objectconstruction:object-construction-qual:0.1
> Could not resolve all files for configuration ':webauthn-server-demo:checkerFramework'.
   > Could not find net.sridharan.objectconstruction:returnsrcvr-checker:0.1-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/returnsrcvr-checker-0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/net/sridharan/objectconstruction/returnsrcvr-checker/0.1-SNAPSHOT/returnsrcvr-checker-0.1-SNAPSHOT.jar
     Required by:
         project :webauthn-server-demo > net.sridharan.objectconstruction:object-construction-checker:0.1
   > Could not find net.sridharan.objectconstruction:returnsrcvr-qual:0.1-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/returnsrcvr-qual-0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/net/sridharan/objectconstruction/returnsrcvr-qual/0.1-SNAPSHOT/returnsrcvr-qual-0.1-SNAPSHOT.jar
     Required by:
         project :webauthn-server-demo > net.sridharan.objectconstruction:object-construction-checker:0.1 > net.sridharan.objectconstruction:object-construction-qual:0.1
> Could not resolve all files for configuration ':yubico-util:checkerFramework'.
   > Could not find net.sridharan.objectconstruction:returnsrcvr-checker:0.1-SNAPSHOT.
     Required by:
         project :yubico-util > net.sridharan.objectconstruction:object-construction-checker:0.1
   > Could not find net.sridharan.objectconstruction:returnsrcvr-qual:0.1-SNAPSHOT.
     Required by:
         project :yubico-util > net.sridharan.objectconstruction:object-construction-checker:0.1 > net.sridharan.objectconstruction:object-construction-qual:0.1
> Could not resolve all files for configuration ':yubico-util-scala:checkerFramework'.
   > Could not find net.sridharan.objectconstruction:returnsrcvr-checker:0.1-SNAPSHOT.
     Required by:
         project :yubico-util-scala > net.sridharan.objectconstruction:object-construction-checker:0.1
   > Could not find net.sridharan.objectconstruction:returnsrcvr-qual:0.1-SNAPSHOT.
     Required by:
         project :yubico-util-scala > net.sridharan.objectconstruction:object-construction-checker:0.1 > net.sridharan.objectconstruction:object-construction-qual:0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s

```

**Comment by msridhar** [comment]
I've updated the PR to refer to snapshot builds now, which should fix the second issue @kelloggm identified.  I tried building with @kellogm's hacked version, and got the following error:
```
$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> zip file name too long
> zip file name too long
> zip file name too long
> zip file name too long
> zip file name too long
```
Seems unrelated to our checker, though I'm not 100% sure.

**Comment by kelloggm** [comment]
This is related to an interaction between our checker and the Gradle plugin; see https://github.com/kelloggm/checkerframework-gradle-plugin/pull/18.

Add `skipVersionCheck = true` to the `checkerFramework` block in the `build.gradle` to work around the problem.

**Comment by msridhar** [comment]
> This is related to an interaction between our checker and the Gradle plugin; see [kelloggm/checkerframework-gradle-plugin#18](https://github.com/kelloggm/checkerframework-gradle-plugin/pull/18).
> 
> Add `skipVersionCheck = true` to the `checkerFramework` block in the `build.gradle` to work around the problem.

Ok, with this change, I confirmed that the instructions work for the `object-construction-checker` branch of https://github.com/kelloggm/java-webauthn-server/tree/object-construction-checker and I get some errors from our checker.  Here are the changes I made to the `build.gradle` file:
```diff
diff --git a/build.gradle b/build.gradle
index 3e2d30eb..f2f50d07 100644
--- a/build.gradle
+++ b/build.gradle
@@ -51,6 +51,7 @@ subprojects {
     mavenLocal()

     maven { url "http://repo.maven.apache.org/maven2" }
+    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
   }

   apply plugin: 'org.checkerframework'
@@ -72,12 +73,13 @@ subprojects { project ->


   checkerFramework {
+    skipVersionCheck = true
     checkers = ['org.checkerframework.checker.objectconstruction.ObjectConstructionChecker']
     extraJavacArgs = ['-AsuppressWarnings=type.anno.before']
   }
   dependencies {
-    checkerFramework 'net.sridharan.objectconstruction:object-construction-checker:0.1'
-    implementation 'net.sridharan.objectconstruction:object-construction-qual:0.1'
+    checkerFramework 'net.sridharan.objectconstruction:object-construction-checker:0.1.1-SNAPSHOT'
+    implementation 'net.sridharan.objectconstruction:object-construction-qual:0.1.1-SNAPSHOT'
   }

   tasks.withType(JavaCompile) {
```

@kelloggm @mernst I think we can go ahead and merge this.

**Comment by kelloggm** [comment]
LGTM

**Pull request merged**
