### PR TITLE
make the count an error, so that maven doesn't eat it

### PR DESCRIPTION
**Pull request by kelloggm**
I'm getting deja vu, since this definitely happened last time I did this too and I just forgot :(

### CODE REVIEW

**Comment by kelloggm** [comment]
and the reason I didn't make this change before becomes apparent: this makes all our tests fail

**Review by msridhar — APPROVED** [review]
Will the compilation fail because of these `ERROR`-level messages?

**Comment by msridhar** [comment]
> and the reason I didn't make this change before becomes apparent: this makes all our tests fail

maybe we just need to extract `javac` commands to get these counts in cases where maven is used?

**Comment by kelloggm** [comment]
@msridhar I think this latest version is the sweet spot. I've made it a warning, which won't fail compilation (or our tests), but will still show up in Maven's logs

**Review by msridhar — APPROVED** [review]
re-stamping for WARNING level

**Pull request merged**
